name: 'Git Action Slack Notification'
description: 'Slack notification sent by Git Actions'
author: 'Senzing'
branding:
  icon: 'message-square'
  color: 'purple'
runs:
  using: 'docker'
  image: 'docker://senzing/git-action-slack-notification:1.0.0'
