name: CI Test Build On Push Event For A Commit

on:
  push:
    branches-ignore:
      - master

jobs:
  ciTestBuildOnBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print Environment Variables
        run: printenv
      - name: Build Docker Image
        id: build_docker_image
        run: |
          docker build --tag git-action-slack-notification:${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} \
            --build-arg "GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}" \
            --build-arg "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}" \
            build/docker